# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcSelect < Formula
  desc "Shell-level AI provider isolation for Claude Code"
  homepage "https://github.com/matiastang/cc-select"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matiastang/cc-select/releases/download/v0.0.1/cc-select_0.0.1_darwin_amd64.tar.gz"
      sha256 "f1650a7d21295bdfb5ca549c88eb9d43863513bb88f478dcf1e433319d6ba5bc"

      define_method(:install) do
        bin.install "cc-select"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matiastang/cc-select/releases/download/v0.0.1/cc-select_0.0.1_darwin_arm64.tar.gz"
      sha256 "07600796464e308d20df87df3b6fe3e8b21e5fb53d9449b34af7d7dc20c21a26"

      define_method(:install) do
        bin.install "cc-select"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matiastang/cc-select/releases/download/v0.0.1/cc-select_0.0.1_linux_amd64.tar.gz"
      sha256 "8d3ebcd0b250038b84bec69cd41081a8a1301edb06cb6a9b692f89d6d990cef3"
      define_method(:install) do
        bin.install "cc-select"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matiastang/cc-select/releases/download/v0.0.1/cc-select_0.0.1_linux_arm64.tar.gz"
      sha256 "7ba68faf6cc63b7d2c9a7f4e2740461b5d35337b43aeb7f1a7c804fc729aeb45"
      define_method(:install) do
        bin.install "cc-select"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell integration, run:
        cc-select init >> ~/.zshrc
      Then reload your shell or run `source ~/.zshrc`.
      On bash use ~/.bashrc instead.
    EOS
  end

  test do
    system "#{bin}/cc-select", "--version"
  end
end
